name: CI and Release GGML

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [created]

jobs:
  build-and-release:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    env:
      GGML_NLOOP: 3
      GGML_NITER: 1
      GGML_N_THREADS: 2

    steps:
    - uses: actions/checkout@v3

    - name: Dependencies for Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install llvm

    - name: Create Build Environment
      run: mkdir build

    - name: Configure CMake
      working-directory: ./build
      run: cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DGGML_METAL=OFF ..

    - name: Build
      working-directory: ./build
      run: make

    - name: Test
      working-directory: ./build
      run: ctest --verbose --timeout 900

    - name: Package Library
      run: |
        mkdir -p ggml-lib
        cp build/src/libggml.* ggml-lib/
        tar -czvf ggml-lib-${{ matrix.os }}.tar.gz ggml-lib

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ggml-lib-${{ matrix.os }}
        path: ggml-lib-${{ matrix.os }}.tar.gz

    - name: Release
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'release' && github.event.action == 'created'
      with:
        files: ggml-lib-${{ matrix.os }}.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}